-- 080: tabela de clubes canonicos da AFPORTO, para acabar com o mesmo
-- clube escrito de formas diferentes (confirmado com dados reais: o
-- Gondomar SC em 5 grafias diferentes, "Atanese"/"CR Ataense").
-- Lista fornecida pelo fundador (nao inventada/pesquisada -- sem
-- acesso a internet neste ambiente para ir buscar a lista oficial),
-- incluindo 3 correcoes dele: Escola de Benfica - Paredes (no USC
-- Baltar), USC Baltar, e Rio Mau em Penafiel.
-- Leitura publica (necessaria para o formulario de inscricao livre,
-- que nao exige sessao). Tabela editavel pelo admin para crescer/
-- corrigir ao longo do tempo -- nao pretende ser exaustiva ja.

INSERT INTO public.clubes_afporto (nome, concelho) VALUES
  ('Futebol Clube do Porto', 'Porto'),
  ('Boavista Futebol Clube', 'Porto'),
  ('Sport Clube Salgueiros', 'Porto'),
  ('Futebol Clube Foz', 'Porto'),
  ('Associação Juvenil Escola de Futebol Hernâni Gonçalves', 'Porto'),
  ('Ramaldense Futebol Clube', 'Porto'),
  ('Panteras Negras Footballers Club', 'Porto'),
  ('Centro de Atletismo do Porto', 'Porto'),
  ('Gondomar Sport Clube', 'Gondomar'),
  ('Sport Clube Rio Tinto', 'Gondomar'),
  ('Clube Atlético Rio Tinto', 'Gondomar'),
  ('Estrelas Futebol Clube de Fânzeres', 'Gondomar'),
  ('Clube Desportivo São Pedro da Cova', 'Gondomar'),
  ('União Desportiva Sousense', 'Gondomar'),
  ('Gens Sport Clube', 'Gondomar'),
  ('Melres Desporto e Cultura', 'Gondomar'),
  ('Sport Clube Montezelo', 'Gondomar'),
  ('Clube Recreativo Ataense', 'Gondomar'),
  ('Clube Recreativo Zebreirense', 'Gondomar'),
  ('Valadares Gaia Futebol Clube', 'Vila Nova de Gaia'),
  ('Sporting Clube Coimbrões', 'Vila Nova de Gaia'),
  ('Sport Clube Os Dragões Sandinenses', 'Vila Nova de Gaia'),
  ('Futebol Clube de Avintes', 'Vila Nova de Gaia'),
  ('Clube de Futebol São Félix da Marinha', 'Vila Nova de Gaia'),
  ('Clube de Futebol de Serzedo', 'Vila Nova de Gaia'),
  ('Sporting Clube Villa', 'Vila Nova de Gaia'),
  ('Canelas Futebol Clube 2010', 'Vila Nova de Gaia'),
  ('Leixões Sport Club', 'Matosinhos'),
  ('Padroense Futebol Clube', 'Matosinhos'),
  ('Leça Futebol Clube', 'Matosinhos'),
  ('Futebol Clube Perafita', 'Matosinhos'),
  ('Futebol Clube Infesta', 'Matosinhos'),
  ('Sport Clube Senhora da Hora', 'Matosinhos'),
  ('Futebol Clube Maia Lidador', 'Maia'),
  ('Futebol Clube Pedras Rubras', 'Maia'),
  ('Sport Clube Castêlo da Maia', 'Maia'),
  ('Folgosa da Maia Futebol Clube', 'Maia'),
  ('Pedrouços Atlético Clube', 'Maia'),
  ('Ermesinde Sport Clube 1936', 'Valongo'),
  ('Atlético Clube Alfenense', 'Valongo'),
  ('União Desportiva Valonguense', 'Valongo'),
  ('Clube Desportivo Sobrado', 'Valongo'),
  ('Sporting Clube Campo', 'Valongo'),
  ('União Sport Club de Paredes', 'Paredes'),
  ('Rebordosa Atlético Clube', 'Paredes'),
  ('Aliança Futebol Clube de Gandra', 'Paredes'),
  ('Sport Clube Nun''Álvares', 'Paredes'),
  ('Futebol Clube Cête', 'Paredes'),
  ('Imperial Sport Clube Sobreirense', 'Paredes'),
  ('Escola de Benfica - Paredes', 'Paredes'),
  ('USC Baltar', 'Paredes'),
  ('Futebol Clube Penafiel', 'Penafiel'),
  ('AVS Futebol SAD', 'Penafiel'),
  ('Associação Desportiva Marco 09', 'Penafiel'),
  ('Futebol Clube Alpendorada', 'Penafiel'),
  ('Rio Mau', 'Penafiel'),
  ('Futebol Clube Paços de Ferreira', 'Paços de Ferreira'),
  ('Sport Clube Freamunde', 'Paços de Ferreira'),
  ('Clube Desportivo Águias de Eiriz', 'Paços de Ferreira'),
  ('Clube Desportivo Leões Seroa', 'Paços de Ferreira'),
  ('Clube Cultural e Recreativo de Raimonda', 'Paços de Ferreira'),
  ('Amarante Futebol Clube', 'Amarante'),
  ('Atlético Clube Vila Meã', 'Amarante'),
  ('Grupo Desportivo Cultural Vila Caiz', 'Amarante'),
  ('Lomba Sport Clube Amarante', 'Amarante'),
  ('Futebol Clube Tirsense', 'Santo Tirso'),
  ('Clube Desportivo das Aves', 'Santo Tirso'),
  ('Futebol Clube Vilarinho', 'Santo Tirso'),
  ('União Desportiva de Roriz', 'Santo Tirso'),
  ('Monte Córdova Futebol Clube', 'Santo Tirso'),
  ('Clube Desportivo Trofense', 'Trofa'),
  ('Atlético Clube Bougadense', 'Trofa'),
  ('Futebol Clube São Romão', 'Trofa'),
  ('Rio Ave Futebol Clube', 'Vila do Conde'),
  ('Associação Desportiva Labruge', 'Vila do Conde'),
  ('Sport Clube Vilar do Pinheiro', 'Vila do Conde'),
  ('Varzim Sport Club', 'Póvoa de Varzim'),
  ('Atlético Clube da Póvoa de Varzim', 'Póvoa de Varzim'),
  ('Clube Desportivo da Póvoa', 'Póvoa de Varzim'),
  ('Futebol Clube Felgueiras 1932', 'Felgueiras'),
  ('Futebol Clube Lixa', 'Felgueiras'),
  ('Futebol Clube Lagares', 'Felgueiras'),
  ('Associação Desportiva Várzea Futebol Clube', 'Felgueiras'),
  ('União Desportiva Torrados', 'Felgueiras'),
  ('Associação Desportiva de Lousada', 'Lousada'),
  ('Aparecida Futebol Clube', 'Lousada'),
  ('Associação Desportiva de Lustosa', 'Lousada'),
  ('Futebol Clube do Marco', 'Marco de Canaveses'),
  ('Futebol Clube Vila Boa de Quires', 'Marco de Canaveses'),
  ('Futebol Clube Vila Boa do Bispo', 'Marco de Canaveses'),
  ('Associação Desportiva de Baião', 'Baião'),
  ('Futebol Clube Frende', 'Baião');